### ISSUE TITLE
Recursive support and multiple files

### ISSUE THREAD

**Issue by sukumargv** [herrstucki/dbf2dsv#4]
Is there a way to convert multiple dbf files at once? @herrstucki

**Comment by jstcki** [comment]
I usually create another script or Makefile for that. See https://github.com/interactivethings/swiss-maps/blob/master/Makefile#L311-L330 for an example.

**Comment by sukumargv** [comment]
I am not really an extensive programmer my self. I will see what I can do. But, Thanks anyway.

**Comment by jstcki** [comment]
Here's a short example for a `Makefile`

``` make
all: foo.tsv bar.tsv baz.tsv

%.tsv: %.dbf
    node_modules/.bin/dbf2dsv -o $@ -- $<
```

Running `make` will build the files `foo.tsv, bar.tsv, baz.tsv` from `foo.dbf, bar.dbf, baz.dbf`
