### ISSUE TITLE
Critical error

### ISSUE THREAD

**Issue by sukumargv** [herrstucki/dbf2dsv#5]
I am getting following error for any file

```
/usr/local/lib/node_modules/dbf2dsv/bin/dbf2dsv:33
  .await(function(error) { if (error) throw error; });
                                      ^

Error: ENXIO: no such device or address, read
    at Error (native)
```

**Comment by jstcki** [comment]
Sounds like a problem with your specific setup. Can you give me an example of the command you're running? Which operating system are you on?

**Comment by jstcki** [comment]
In any case, I don't think it's an issue of this library, therefore I'm closing this. Feel free to add more information though, and I'll see where I can help.

**Comment by sukumargv** [comment]
I am running on OS X El Captain. 
I was trying to run the following command.
`dbf2dsv --out=foo.csv --delimiter="," -- foo.dbf`

**Comment by jstcki** [comment]
Hmm, I don't really know what's going on, sorry. It _seems_ to be something device-related (see http://www.gnu.org/software/libc/manual/html_node/Error-Codes.html for the `ENXIO` error). Maybe you're trying to access a file on an external hard drive or network storage which isn't mounted?
